version: '3.8'

services:
  api:
    # Ghi đè command mặc định để chạy uvicorn với nhiều workers
    # và tắt chế độ auto-reload, tối ưu cho production.
    command: >
      sh -c "poetry run python cli.py init-db && 
             poetry run uvicorn app.main:api_app --host 0.0.0.0 --port 8000 --workers 4"
    restart: always # Đảm bảo service luôn tự khởi động lại khi có lỗi

  etl:
    # Không cần thay đổi gì cho service etl
    # Nó vẫn sẽ được sử dụng để chạy các tác vụ thủ công hoặc qua cron job
    command: ["tail", "-f", "/dev/null"]
