version: '3.8'

services:
  # Service để chạy API server FastAPI
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icount_api
    restart: unless-stopped
    env_file:
      - .env # Tải các biến môi trường từ tệp .env
    ports:
      - 8000:8000
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - icount_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Service "one-off" để chạy các tác vụ ETL
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icount_etl
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - icount_network
    depends_on:
      api:
        condition: service_healthy # Chỉ chạy khi service 'api' đã sẵn sàng
    # Ghi đè CMD mặc định để service này không tự chạy
    command: ["tail", "-f", "/dev/null"]

networks:
  icount_network:
    driver: bridge

volumes:
  app_data:
  app_logs:
