version: 1
disable_existing_loggers: false

filters:
  below_warning:
    (): app.utils.logger.MaxLevelFilter
    level: WARNING

formatters:
  default:
    format: "%(asctime)s - %(levelname)s - [%(filename)s] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(levelname)s %(name)s %(filename)s %(lineno)d %(message)s"

handlers:
  stdout:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
    filters: [below_warning]
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: default
    stream: ext://sys.stderr
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: default
    filename: logs/app.log
    when: midnight
    interval: 1
    backupCount: 14
    encoding: utf-8
  file_json:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/app.json.log
    when: midnight
    interval: 1
    backupCount: 14
    encoding: utf-8

root:
  level: INFO
  handlers: [stdout, stderr, file, file_json]
