store:
  source_table: dbo.store
  dest_table: dim_stores
  incremental: false
  rename_map:
    tid: store_id
    name: store_name
  cleaning_rules:
    - column: store_name  # Áp dụng trên cột SAU KHI đã rename
      action: rstrip      # Hành động là loại bỏ khoảng trắng cuối chuỗi

num_crowd:
  source_table: dbo.num_crowd
  dest_table: fact_traffic
  incremental: true
  timestamp_col: recordtime
  partition_cols: [year, month]
  rename_map:
    recordtime: recorded_at
    in_num: visitors_in
    out_num: visitors_out
    position: device_position
    storeid: store_id
  cleaning_rules:
    - column: device_position
      action: rstrip

ErrLog:
  source_table: dbo.ErrLog
  dest_table: fact_errors
  incremental: true
  timestamp_col: LogTime
  partition_cols: [year, month]
  rename_map:
    ID: log_id
    storeid: store_id
    DeviceCode: device_code
    LogTime: logged_at
    Errorcode: error_code
    ErrorMessage: error_message
  cleaning_rules:
    - column: error_message
      action: rstrip
