[production]
DB_HOST = "SRVBMS\SQLEXPRESS"
DB_PORT = 1433
DB_NAME = "statistic"
DB_USER = "sa"
DB_PASS = "bms123"

[development]
DB_HOST = "MSSQL"
DB_PORT = 1433
DB_NAME = "statistic"
DB_USER = "sa"
DB_PASS = "Admin@123"
