PROJECT_NAME = "iCount People Application"
DESCRIPTION = "Application to analyze the number of people entering and leaving the store."

DB_HOST = "MSSQL"
DB_PORT = 1433
DB_DRIVER = "SQL Server"
DB_NAME = "statistic"
DB_USER = "sa"
DB_PASS = "Admin@123"
